name: Go Application CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Initialize Go module
        run: go mod init my-go-app

      - name: Get dependencies
        run: go mod tidy

      - name: Build the application
        run: go build -o my-go-app

      - name: Run tests
        run: go test ./...
